[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.25"
thiserror = "1.0"

[lib]
name = "my_project"
path = "src/lib.rs"

[[bin]]
name = "my_project"
path = "src/main.rs"
