[package]
name = "my_project"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = "0.5"
sqlx-macros = "0.5"
tokio = { version = "1", features = ["full"] }

[lib]
name = "my_project"
path = "src/lib.rs"

[[bin]]
name = "my_project"
path = "src/main.rs"
